# Generated by Django 4.2.5 on 2023-10-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('expense_type', models.CharField(choices=[('equally', 'equally'), ('exact', 'exact'), ('percentage', 'percentage')], default='equally', max_length=20)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('due', 'due')], default='due', max_length=4)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='expense.expense')),
            ],
        ),
    ]
