# Generated by Django 4.2.5 on 2023-10-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='expense',
            name='involved',
            field=models.ManyToManyField(blank=True, null=True, related_name='expenses_involved', to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='expenses_paid', to='userprofile.profile'),
        ),
    ]
